cert-manager:
  azureIdentity:
    resourceID: ${cert_manager_resource_id}
    clientID: ${cert_manager_client_id}
  clusterIssuers:
    letsencrypt:
      enabled: true
    acme:
      solvers:
        - dns01:
            azuredns:
              subscriptionID: ${subscription_id}
              resourceGroupName: ${resource_group_name}
              hostedZoneName: ${cluster_info.base_domain}
              # Azure Cloud Environment, default to AzurePublicCloud
              environment: AzurePublicCloud
          selector:
            dnsZones:
              - ${cluster_info.base_domain}
        - http01:
            ingress: {}
  replicaCount: 2
  podLabels:
    aadpodidbinding: cert-manager
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi
  webhook:
    replicaCount: 2
    resources:
      limits:
        memory: 24Mi
      requests:
        cpu: 10m
        memory: 16Mi
  cainjector:
    replicaCount: 2
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
