---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $.Values.clusterIssuers.default.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selfSigned: {}
{{- if index $.Values "cert-manager" }}
{{- if $.Values.clusterIssuers.ca.tlsCrt }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $.Values.issuers.ca.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ca:
    secretName: ca-key-pair
{{- end }}
{{- if index $.Values.clusterIssuers }}
{{- if index $.Values.clusterIssuers.letsencrypt }}
{{- if index $.Values.clusterIssuers.letsencrypt.enabled }}
{{- range $name, $issuer := index $.Values.clusterIssuers.letsencrypt.issuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  acme:
    email: {{ $issuer.email }}
    server: {{ $issuer.server }}
    privateKeySecretRef:
      name: {{ $name }}
    {{ index $.Values.clusterIssuers.letsencrypt.acme | toYaml | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
